# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# STEP 1: Imports
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
import joblib

# STEP 2: Split data
X = df[["temperature", "gas"]]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# STEP 3: SCALE DATA (VERY IMPORTANT)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# STEP 4: Train model
model = MLPClassifier(hidden_layer_sizes=(16, 8), max_iter=500)
model.fit(X_train_scaled, y_train)

# STEP 5: Accuracy
print("Accuracy:", model.score(X_test_scaled, y_test))

test_samples = [
    [25, 150],
    [30, 400],
    [35, 700],
    [40, 850],
    [28, 250]
]

labels = ["Normal", "Warning", "Danger"]

for sample in test_samples:
    sample_scaled = scaler.transform([sample])
    pred = model.predict(sample_scaled)
    print(f"Temp={sample[0]}, Gas={sample[1]} → {labels[pred[0]]}")

joblib.dump(model, "gas_model.pkl")
joblib.dump(scaler, "scaler.pkl")

from google.colab import files

files.download("gas_model.pkl")
files.download("scaler.pkl")